import { Toaster } from 'react-hot-toast'
import Footer from './components/footer/Footer'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alex Dev',
  description: 'Generated by Clocicov Alexandru',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
          <Toaster />
        </header>
        <main>{children}</main>
        <footer >
          <Footer />
        </footer>
        </body>
    </html>
  )
}
